import { lowlight } from "lowlight/lib/core";
import css from "highlight.js/lib/languages/css";
import js from "highlight.js/lib/languages/javascript";
import ts from "highlight.js/lib/languages/typescript";
import html from "highlight.js/lib/languages/xml";
import java from "highlight.js/lib/languages/java";
import python from "highlight.js/lib/languages/python";
import c from "highlight.js/lib/languages/c";
import cpp from "highlight.js/lib/languages/cpp";
import csharp from "highlight.js/lib/languages/csharp";
import php from "highlight.js/lib/languages/php";
import swift from "highlight.js/lib/languages/swift";
import ruby from "highlight.js/lib/languages/ruby";
import kotlin from "highlight.js/lib/languages/kotlin";
import bash from "highlight.js/lib/languages/bash";
import go from "highlight.js/lib/languages/go";
import rust from "highlight.js/lib/languages/rust";
import r from "highlight.js/lib/languages/r";
import dart from "highlight.js/lib/languages/dart";
import perl from "highlight.js/lib/languages/perl";
import julia from "highlight.js/lib/languages/julia";
import matlab from "highlight.js/lib/languages/matlab";
import lua from "highlight.js/lib/languages/lua";
import objectivec from "highlight.js/lib/languages/objectivec";
import groovy from "highlight.js/lib/languages/groovy";
import shell from "highlight.js/lib/languages/shell";
import scala from "highlight.js/lib/languages/scala";
import vbnet from "highlight.js/lib/languages/vbnet";
import crystal from "highlight.js/lib/languages/crystal";
import elixir from "highlight.js/lib/languages/elixir";
import lisp from "highlight.js/lib/languages/lisp";
import prolog from "highlight.js/lib/languages/prolog";
import ada from "highlight.js/lib/languages/ada";
import scheme from "highlight.js/lib/languages/scheme";
import sql from "highlight.js/lib/languages/sql";


lowlight.registerLanguage("html", html);
lowlight.registerLanguage("css", css);
lowlight.registerLanguage("js", js);
lowlight.registerLanguage("ts", ts);
lowlight.registerLanguage("java", java);
lowlight.registerLanguage("python", python);
lowlight.registerLanguage("c", c);
lowlight.registerLanguage("cpp", cpp);
lowlight.registerLanguage("csharp", csharp);
lowlight.registerLanguage("php", php);
lowlight.registerLanguage("swift", swift);
lowlight.registerLanguage("ruby", ruby);
lowlight.registerLanguage("kotlin", kotlin);
lowlight.registerLanguage("bash", bash);
lowlight.registerLanguage("go", go);
lowlight.registerLanguage("rust", rust);
lowlight.registerLanguage("r", r);
lowlight.registerLanguage("dart", dart);
lowlight.registerLanguage("perl", perl);
lowlight.registerLanguage("julia", julia);
lowlight.registerLanguage("matlab", matlab);
lowlight.registerLanguage("lua", lua);
lowlight.registerLanguage("objectivec", objectivec);
lowlight.registerLanguage("groovy", groovy);
lowlight.registerLanguage("shell", shell);
lowlight.registerLanguage("scala", scala);
lowlight.registerLanguage("vbnet", vbnet);
lowlight.registerLanguage("crystal", crystal);
lowlight.registerLanguage("elixir", elixir);
lowlight.registerLanguage("lisp", lisp);
lowlight.registerLanguage("prolog", prolog);
lowlight.registerLanguage("ada", ada);
lowlight.registerLanguage("scheme", scheme);
lowlight.registerLanguage("sql", sql);

export default lowlight;