export const NEXT_PUBLIC_FIREBASE_API_KEY: string =
  process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? "";
export const NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string =
  process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? "";
export const NEXT_PUBLIC_FIREBASE_PROJECT_ID: string =
  process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "";
export const NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string =
  process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? "";
export const NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? "";
export const NEXT_PUBLIC_FIREBASE_APP_ID: string =
  process.env.NEXT_PUBLIC_FIREBASE_APP_ID ?? "";
export const NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: string =
  process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID ?? "";
export const NEXT_PUBLIC_FIREBASE_DATABASE_URL: string =
  process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL ?? "";
